architecture:
  type: gru
  hidden_size: [512, 256]
  num_layers: 1
  rnn_dropout: 0.0
  fc_layer_dropout: [0.2, 0.3]

batch_size: 128
lr: 0.00001
epochs: 20

horizons:
  train: 60
  pred: 30

loss: mse
normalisation: z-score

features: ['cbg', 'basal', 'gsr', 'carbInput', 'bolus']

repetitions: 3
