architecture:
  type: rnn
  hidden_size: 64

batch_size: 128
lr: 0.001
epochs: 10

horizons:
  train: 60
  pred: 30

loss: mse

# first features needs to be cbg, this is what we want to predict
features: ['cbg', 'carbInput', 'bolus']


